### ISSUE TITLE
Masking paddy field in Malaysia

### ISSUE THREAD

**Issue by huseinzol05** [malaysia-ai/datasets#1]
We can use satellite images from mapbox, eg, https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11/tiles/14/12794/8030@2x?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw

How hard to do at least semisupervised manner?

1. Annotate 50 satellite images.
2. Finetune masking models.
3. Iterate active learning.

@khursani8

**Comment by huseinzol05** [comment]
https://gis.stackexchange.com/questions/7430/what-ratio-scales-do-google-maps-zoom-levels-correspond-to

**Comment by khursani8** [comment]
To setup not that hard with label studio, just need the data to setup

**Comment by khursani8** [comment]
I think we can start with weakly supervised model using CAM feature to get segmentation label, after that improve image label quality and then use that high quality to finetune on any segmentation model(need to do more research which one better, can use unet for any beginner want to contribute for hacktoberfest)

**Comment by khursani8** [comment]
Open dataset for rice seedling(not paddy field segmentation) dataset https://github.com/aipal-nchu/RiceSeedlingDataset
Can use trained object detection model from this dataset to create CAM feature for weak label
